# Generated by Django 6.0.3 on 2026-04-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_create_album',
            field=models.BooleanField(default=False),
        ),
    ]
