# Generated by Django 6.0.3 on 2026-05-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_can_create_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='can_create_album',
            field=models.BooleanField(default=False, verbose_name='Может создавать альбомы'),
        ),
    ]
