version: "3.9"

services:
  web:
    build: .
    container_name: vitochka_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: vitochka.settings.dev

  db:
    image: postgres:16
    container_name: vitochka_db_dev
    environment:
      POSTGRES_DB: vitochka
      POSTGRES_USER: vitochka_user
      POSTGRES_PASSWORD: vitochka_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  static_volume:
  media_volume:
  postgres_data: