# Generated by Django 4.2.19 on 2025-03-05 11:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viapp', '0002_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='album',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_albums', to=settings.AUTH_USER_MODEL, verbose_name='Доступ для пользователей'),
        ),
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание фотографии'),
        ),
        migrations.AddField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название фотографии'),
        ),
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True, default='Без описания', verbose_name='Описание альбома'),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название альбома'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos/', verbose_name=' Фотография'),
        ),
    ]
