# Generated by Django 4.2.19 on 2025-03-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viapp', '0003_album_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['order'], 'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AddField(
            model_name='photo',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
