# Generated by Django 6.0.3 on 2026-05-22 11:38

import viapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viapp', '0005_alter_album_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos/', validators=[viapp.models.validate_image, viapp.models.validate_size], verbose_name=' Фотография'),
        ),
    ]
