# Generated by Django 6.0.3 on 2026-06-01 10:03

import django.core.validators
import viapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viapp', '0006_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos/', validators=[viapp.models.validate_image, viapp.models.validate_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name=' Фотография'),
        ),
    ]
